-- BookMind Supabase Schema
-- Run this entire file in the Supabase SQL editor (Dashboard → SQL Editor → New Query)

-- Books table: replaces storage/library.json
-- Each row is one book belonging to one user.
CREATE TABLE IF NOT EXISTS books (
  id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  slug        TEXT NOT NULL,
  title       TEXT NOT NULL,
  author      TEXT DEFAULT 'Unknown Author',
  status      TEXT DEFAULT 'extracted',   -- 'extracted' | 'processing' | 'indexed' | 'ready' | 'failed'
  progress    INTEGER DEFAULT 0,
  added_at    TIMESTAMPTZ DEFAULT NOW(),
  metadata    JSONB DEFAULT '{}',         -- category, cover, readingTime, pdfPath, wordCount
  UNIQUE(user_id, slug)
);

-- Knowledge table: replaces every JSON file under storage/knowledge/
-- key examples:
--   'package'             → placeholder KnowledgePackage written at upload time
--   'index'               → BookIndex generated by Gemini
--   'chapters/intro'      → ChapterDetail in default language (English)
--   'chapters/intro.hi'   → ChapterDetail in Hindi
--   'chapters/intro.de'   → ChapterDetail in German
--   'modes/10'            → LearningMode (10-minute)
--   'modes/30'            → LearningMode (30-minute)
CREATE TABLE IF NOT EXISTS knowledge (
  user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  slug        TEXT NOT NULL,
  key         TEXT NOT NULL,
  data        JSONB NOT NULL,
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (user_id, slug, key)
);

-- Row Level Security: each user can only read/write their own rows
ALTER TABLE books ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users manage own books" ON books
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "users manage own knowledge" ON knowledge
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Indexes
CREATE INDEX IF NOT EXISTS books_user_id_idx ON books(user_id);
CREATE INDEX IF NOT EXISTS knowledge_user_slug_idx ON knowledge(user_id, slug);
